# Generated by Django 5.2.5 on 2026-01-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveusageplan',
            name='user',
        ),
    ]
