# Generated by Django 5.2.5 on 2026-02-03 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0005_delete_expiredprojectsnapshot'),
        ('payments', '0002_remove_liveusageplan_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='prompt_credits',
            field=models.PositiveIntegerField(blank=True, help_text='Used only for platform payments', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_for',
            field=models.CharField(choices=[('live', 'Live App Plan'), ('platform', 'Platform Plan')], default='live', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.CharField(blank=True, choices=[('1_month', '1 Month'), ('6_months', '6 Months'), ('12_months', '12 Months')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='generate.project'),
        ),
        migrations.CreateModel(
            name='PlatformUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_prompts_used', models.PositiveIntegerField(default=0)),
                ('paid_prompt_credits', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
