# Generated by Django 5.2.5 on 2026-02-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_prompt_credits_alter_payment_payment_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='neft_screenshot',
            field=models.ImageField(blank=True, help_text='Screenshot of NEFT transfer (for manual verification)', null=True, upload_to='neft_screenshots/'),
        ),
    ]
