# Generated by Django 5.2.5 on 2026-02-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_neft_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='neft_screenshot',
        ),
        migrations.AddField(
            model_name='payment',
            name='live_neft_screenshot',
            field=models.ImageField(blank=True, help_text='NEFT screenshot for Live project payment', null=True, upload_to='neft/live/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='platform_neft_screenshot',
            field=models.ImageField(blank=True, help_text='NEFT screenshot for Platform credit payment', null=True, upload_to='neft/platform/'),
        ),
    ]
