# Generated by Django 5.2.5 on 2026-01-29 13:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveAppData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_data', to='generate.project')),
            ],
        ),
        migrations.CreateModel(
            name='ExpiredProjectSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_schema', models.JSONField(default=dict)),
                ('workflows', models.JSONField(default=list)),
                ('data_types', models.JSONField(default=dict)),
                ('live_app_data', models.JSONField(default=dict)),
                ('expired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('grace_ended_at', models.DateTimeField()),
                ('reason', models.CharField(default='subscription_expired', max_length=50)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expired_snapshot', to='generate.project')),
            ],
        ),
        migrations.CreateModel(
            name='AppSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('user_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='generate.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_type', models.CharField(choices=[('preview', 'Preview'), ('live', 'Live')], max_length=10)),
                ('ui_schema', models.JSONField(default=dict)),
                ('workflows', models.JSONField(default=list)),
                ('data_types', models.JSONField(default=dict)),
                ('app_data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='generate.project')),
            ],
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'updated_at'], name='generate_pr_user_id_03e6d6_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user'], name='generate_pr_user_id_af902b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('user', 'project_name')},
        ),
        migrations.AddIndex(
            model_name='appsession',
            index=models.Index(fields=['expires_at'], name='generate_ap_expires_f2fc6b_idx'),
        ),
        migrations.AddIndex(
            model_name='appsession',
            index=models.Index(fields=['project', 'user_id'], name='generate_ap_project_b79770_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectversion',
            constraint=models.UniqueConstraint(fields=('project', 'version_type'), name='one_version_per_type_per_project'),
        ),
    ]
