# Generated by Django 5.2.5 on 2026-02-02 07:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_schema', models.JSONField(default=dict)),
                ('workflows', models.JSONField(default=list)),
                ('data_types', models.JSONField(default=dict)),
                ('live_app_data', models.JSONField(default=dict)),
                ('expired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('grace_ended_at', models.DateTimeField()),
                ('reason', models.CharField(default='subscription_expired', max_length=50)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expired_snapshot', to='generate.project')),
            ],
        ),
    ]
