# Generated by Django 5.2.5 on 2026-02-02 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0002_expiredproject_delete_expiredprojectsnapshot'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LiveAppData',
            new_name='BeforeDeployLiveAppData',
        ),
    ]
