# Generated by Django 5.2.5 on 2026-02-03 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0003_rename_liveappdata_beforedeployliveappdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=50)),
                ('value', models.TextField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='element_images/')),
                ('style', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='generate.projectversion')),
            ],
            options={
                'unique_together': {('project_version', 'element_id')},
            },
        ),
    ]
