# Generated by Django 5.2.5 on 2026-02-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0004_imageelement_delete_expiredprojectsnapshot'),
    ]

    operations = [
    ]
