# Generated by Django 5.2.5 on 2026-02-04 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0005_delete_expiredprojectsnapshot'),
    ]

    operations = [

    ]
