# Generated by Django 5.2.5 on 2026-02-23 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0006_delete_expiredprojectsnapshot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imageelement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='imageelement',
            name='project_version',
        ),
        migrations.DeleteModel(
            name='ImageElement',
        ),
    ]
