# Generated by Django 5.2.5 on 2026-02-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generate', '0007_alter_imageelement_unique_together_and_more'),
    ]

    operations = [
    ]
